-- Inserción de ciudades nuevas desde dataset DNCP-SIPE
-- Idempotente: ON CONFLICT (slug) DO NOTHING. Seguro de correr varias veces.
-- 113 ciudades nuevas (umbral: 2+ empresas). lat/lng quedan NULL para geocodificar luego.
BEGIN;
INSERT INTO cities (name, department, slug, is_active) VALUES
  ('Carmelo Peralta', 'Alto Paraguay', 'carmelo-peralta', true),
  ('Puerto Casado', 'Alto Paraguay', 'puerto-casado', true),
  ('Col.Yguazu', 'Alto Paraná', 'col-yguazu', true),
  ('Iruña', 'Alto Paraná', 'iruna', true),
  ('Itakyry', 'Alto Paraná', 'itakyry', true),
  ('Itaquyry', 'Alto Paraná', 'itaquyry', true),
  ('Juan E. O''Leary', 'Alto Paraná', 'juan-e-o-leary', true),
  ('Juan Leon Mallorquin', 'Alto Paraná', 'juan-leon-mallorquin', true),
  ('Los Cedrales', 'Alto Paraná', 'los-cedrales', true),
  ('Mbaracayu', 'Alto Paraná', 'mbaracayu', true),
  ('Minga Pora', 'Alto Paraná', 'minga-pora', true),
  ('Naranjal', 'Alto Paraná', 'naranjal', true),
  ('San Alberto', 'Alto Paraná', 'san-alberto', true),
  ('San Cristobal', 'Alto Paraná', 'san-cristobal', true),
  ('Santa Fe Del Parana', 'Alto Paraná', 'santa-fe-del-parana', true),
  ('Santa Rosa Del Monday', 'Alto Paraná', 'santa-rosa-del-monday', true),
  ('Yguazu', 'Alto Paraná', 'yguazu', true),
  ('Ñacunday', 'Alto Paraná', 'nacunday', true),
  ('Cerro Cora', 'Amambay', 'cerro-cora', true),
  ('San Jorge', 'Asunción', 'san-jorge', true),
  ('Col.Neuland', 'Boquerón', 'col-neuland', true),
  ('Loma Plata', 'Boquerón', 'loma-plata', true),
  ('12 De Junio 1Ra', 'Caaguazú', '12-de-junio-1ra', true),
  ('Col.Santa Teresa', 'Caaguazú', 'col-santa-teresa', true),
  ('J.Eulogio Estigarribia', 'Caaguazú', 'j-eulogio-estigarribia', true),
  ('Jose D. Ocampos', 'Caaguazú', 'jose-d-ocampos', true),
  ('Juan Manuel Frutos', 'Caaguazú', 'juan-manuel-frutos', true),
  ('Repatriacion', 'Caaguazú', 'repatriacion', true),
  ('San Jose De Los Arroyos', 'Caaguazú', 'san-jose-de-los-arroyos', true),
  ('Simon Bolivar', 'Caaguazú', 'simon-bolivar', true),
  ('Tembiapora', 'Caaguazú', 'tembiapora', true),
  ('Vaqueria', 'Caaguazú', 'vaqueria', true),
  ('Yhu', 'Caaguazú', 'yhu', true),
  ('3 De Mayo', 'Caazapá', '3-de-mayo', true),
  ('Abai', 'Caazapá', 'abai', true),
  ('Caazapa', 'Caazapá', 'caazapa', true),
  ('Coronel Maciel', 'Caazapá', 'coronel-maciel', true),
  ('Fulgencio Yegros', 'Caazapá', 'fulgencio-yegros', true),
  ('Maciel', 'Caazapá', 'maciel', true),
  ('San J. Nepomuceno', 'Caazapá', 'san-j-nepomuceno', true),
  ('San Juan Nepomuceno', 'Caazapá', 'san-juan-nepomuceno', true),
  ('Yuty', 'Caazapá', 'yuty', true),
  ('Corpus Christi', 'Canindeyú', 'corpus-christi', true),
  ('Francisco Caballero Alvarez', 'Canindeyú', 'francisco-caballero-alvarez', true),
  ('La Paloma', 'Canindeyú', 'la-paloma', true),
  ('Nueva Esperanza', 'Canindeyú', 'nueva-esperanza', true),
  ('Puerto Adela', 'Canindeyú', 'puerto-adela', true),
  ('San Isidro Del Curuguaty', 'Canindeyú', 'san-isidro-del-curuguaty', true),
  ('Villa Curuguaty', 'Canindeyú', 'villa-curuguaty', true),
  ('Villa Ygatimi', 'Canindeyú', 'villa-ygatimi', true),
  ('Yasy Cañy', 'Canindeyú', 'yasy-cany', true),
  ('Fernando De La Mora - Zona Sur', 'Central', 'fernando-de-la-mora-zona-sur', true),
  ('Fernando De La Mora Zona Norte', 'Central', 'fernando-de-la-mora-zona-norte', true),
  ('Mariano Roque Alonso', 'Central', 'mariano-roque-alonso', true),
  ('Nueva Italia', 'Central', 'nueva-italia', true),
  ('San Antonio', 'Central', 'san-antonio', true),
  ('San Miguel', 'Central', 'san-miguel', true),
  ('Villeta', 'Central', 'villeta', true),
  ('Ypacarai', 'Central', 'ypacarai', true),
  ('Ã?Emby', 'Central', 'a-emby', true),
  ('Yby Ya U', 'Concepción', 'yby-ya-u', true),
  ('Yby Yau', 'Concepción', 'yby-yau', true),
  ('Arroyos Y Esteros', 'Cordillera', 'arroyos-y-esteros', true),
  ('Eusebio Ayala', 'Cordillera', 'eusebio-ayala', true),
  ('Piribebuy', 'Cordillera', 'piribebuy', true),
  ('Tobati', 'Cordillera', 'tobati', true),
  ('Borja', 'Guairá', 'borja', true),
  ('Mauricio Jose Troche', 'Guairá', 'mauricio-jose-troche', true),
  ('Paso Yobai', 'Guairá', 'paso-yobai', true),
  ('Alto Verá', 'Itapúa', 'alto-vera', true),
  ('Bella Vista', 'Itapúa', 'bella-vista', true),
  ('Cambyreta', 'Itapúa', 'cambyreta', true),
  ('Capitan Miranda', 'Itapúa', 'capitan-miranda', true),
  ('Carlos A. Lopez', 'Itapúa', 'carlos-a-lopez', true),
  ('Carlos Antonio López', 'Itapúa', 'carlos-antonio-lopez', true),
  ('Edelira', 'Itapúa', 'edelira', true),
  ('General Delgado', 'Itapúa', 'general-delgado', true),
  ('Gral. Argtigas', 'Itapúa', 'gral-argtigas', true),
  ('Itapua Poty', 'Itapúa', 'itapua-poty', true),
  ('Jose Leandro Oviedo', 'Itapúa', 'jose-leandro-oviedo', true),
  ('La Paz', 'Itapúa', 'la-paz', true),
  ('Maria Auxiliadora', 'Itapúa', 'maria-auxiliadora', true),
  ('Mayor Otaño', 'Itapúa', 'mayor-otano', true),
  ('Natalio', 'Itapúa', 'natalio', true),
  ('Pirapó', 'Itapúa', 'pirapo', true),
  ('San Cosme Y Damian', 'Itapúa', 'san-cosme-y-damian', true),
  ('San Juan Del Parana', 'Itapúa', 'san-juan-del-parana', true),
  ('San Pedro Del Parana', 'Itapúa', 'san-pedro-del-parana', true),
  ('San Rafael Del Paraná', 'Itapúa', 'san-rafael-del-parana', true),
  ('Tomas Romero Pereira', 'Itapúa', 'tomas-romero-pereira', true),
  ('Yatytay', 'Itapúa', 'yatytay', true),
  ('San Juan Bautista', 'Misiones', 'san-juan-bautista', true),
  ('Santiago', 'Misiones', 'santiago', true),
  ('Carapegua', 'Paraguarí', 'carapegua', true),
  ('La Colmena', 'Paraguarí', 'la-colmena', true),
  ('Mbuyapey', 'Paraguarí', 'mbuyapey', true),
  ('Paraguari', 'Paraguarí', 'paraguari', true),
  ('Pirayu', 'Paraguarí', 'pirayu', true),
  ('Quiindy', 'Paraguarí', 'quiindy', true),
  ('Yaguaron', 'Paraguarí', 'yaguaron', true),
  ('Ybycui', 'Paraguarí', 'ybycui', true),
  ('Benjamin Aceval(Monte Sociedad', 'Presidente Hayes', 'benjamin-aceval-monte-sociedad', true),
  ('Boqueron', 'Presidente Hayes', 'boqueron', true),
  ('Nanawa', 'Presidente Hayes', 'nanawa', true),
  ('25 De Diciembre', 'San Pedro', '25-de-diciembre', true),
  ('Chore', 'San Pedro', 'chore', true),
  ('Gral. E.Aquino', 'San Pedro', 'gral-e-aquino', true),
  ('Guayaibi', 'San Pedro', 'guayaibi', true),
  ('Itacurubi Del Rosario', 'San Pedro', 'itacurubi-del-rosario', true),
  ('Santa Rosa Del Aguaray', 'San Pedro', 'santa-rosa-del-aguaray', true),
  ('Union', 'San Pedro', 'union', true),
  ('Barrio Loma Clavel', 'Ñeembucú', 'barrio-loma-clavel', true),
  ('General José Eduvigis Díaz', 'Ñeembucú', 'general-jose-eduvigis-diaz', true)
ON CONFLICT (slug) DO NOTHING;
COMMIT;

-- Verificación: SELECT count(*) FROM cities;  -- debería sumar hasta 113 nuevas